<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\File;

class InstallerController extends Controller
{
    public function index()
    {
        if (config('app.installed')) {
            return redirect('/');
        }

        return view('installer.index');
    }

    public function install(Request $request)
    {
        $request->validate([
            'app_name' => 'required|string|max:255',
            'db_host' => 'required|string',
            'db_port' => 'required|numeric',
            'db_database' => 'required|string',
            'db_username' => 'required|string',
            'db_password' => 'nullable|string',
        ]);

        try {
            if (empty(config('app.key'))) {
                Artisan::call('key:generate', ['--force' => true]);
            }

            // 1. Update .env file
            $this->updateEnv([
                'APP_NAME' => '"' . $request->app_name . '"',
                'APP_URL' => '"' . url('/') . '"',
                'DB_CONNECTION' => 'mysql',
                'DB_HOST' => $request->db_host,
                'DB_PORT' => $request->db_port,
                'DB_DATABASE' => $request->db_database,
                'DB_USERNAME' => $request->db_username,
                'DB_PASSWORD' => $request->db_password ?? '',
                'APP_INSTALLED' => 'true',
            ]);

            // 2. Clear config cache to use new env
            Artisan::call('config:clear');

            config()->set('database.default', env('DB_CONNECTION', 'mysql'));
            config()->set('database.connections.mysql.host', $request->db_host);
            config()->set('database.connections.mysql.port', (int) $request->db_port);
            config()->set('database.connections.mysql.database', $request->db_database);
            config()->set('database.connections.mysql.username', $request->db_username);
            config()->set('database.connections.mysql.password', $request->db_password ?? '');

            try {
                \Illuminate\Support\Facades\DB::purge();
                \Illuminate\Support\Facades\DB::reconnect();
            } catch (\Throwable $e) {
                // ignore - migrations will surface connection errors clearly
            }

            // 3. Run Migrations & Seeders
            Artisan::call('migrate:fresh', ['--force' => true, '--seed' => true]);

            // 4. Link Storage
            Artisan::call('storage:link');

            return response()->json(['success' => true, 'message' => 'Installation successful!']);
        } catch (\Exception $e) {
            return response()->json(['success' => false, 'message' => $e->getMessage()], 500);
        }
    }

    private function updateEnv(array $data)
    {
        $envPath = base_path('.env');
        if (!File::exists($envPath)) {
            $examplePath = base_path('.env.example');

            if (File::exists($examplePath)) {
                $created = @File::copy($examplePath, $envPath);
                if ($created === false) {
                    throw new \RuntimeException('Installer cannot create .env from .env.example. Please ensure the project root is writable.');
                }
            } else {
                $template = implode("\n", [
                    '# ------------------------------------------------------------------------------',
                    '# Sheddy\'s Radio - Environment Configuration',
                    '# Generated by Zerixa Technologies Installer',
                    '# ------------------------------------------------------------------------------',
                    '',
                    'APP_NAME="Sheddy\'s Radio"',
                    'APP_ENV=production',
                    'APP_KEY=',
                    'APP_DEBUG=false',
                    'APP_URL=http://localhost',
                    '',
                    '# ------------------------------------------------------------------------------',
                    '# Database (MySQL)',
                    '# ------------------------------------------------------------------------------',
                    'DB_CONNECTION=mysql',
                    'DB_HOST=127.0.0.1',
                    'DB_PORT=3306',
                    'DB_DATABASE=',
                    'DB_USERNAME=',
                    'DB_PASSWORD=',
                    '',
                    'APP_INSTALLED=false',
                    '',
                ]);

                $created = @File::put($envPath, $template);
                if ($created === false) {
                    throw new \RuntimeException('Installer cannot create .env file. Please ensure the project root is writable.');
                }
            }
        }

        $content = File::exists($envPath) ? File::get($envPath) : '';

        foreach ($data as $key => $value) {
            $pattern = "/^{$key}=.*/m";
            if (preg_match($pattern, $content)) {
                $content = preg_replace($pattern, "{$key}={$value}", $content);
            } else {
                $content .= "\n{$key}={$value}";
            }
        }

        $written = @File::put($envPath, $content);
        if ($written === false) {
            throw new \RuntimeException('Installer cannot write to .env file. Please set correct permissions (writable) for the project root.');
        }
    }
}
